#!/usr/bin/env bash
# Vendor pure, platform-independent leaf files from JetBrains/compose-multiplatform-core
# into :core, verbatim except for this repo's comment style + a provenance header.
#
# Idempotent — re-run after bumping compose-ref.txt to re-sync; `git diff` then
# shows exactly what upstream changed. The vendored files are listed in
# manifest.txt; everything else (engine / renderer / widgets) is hand-written
# and untouched by this script ("fill what's missing").
#
# Usage:   tools/compose-fork/sync.sh
# Env:     CMP_REF=<path>   reuse/!create the clone here (default ../cmp-ref)
set -euo pipefail

kHere="$(cd "$(dirname "$0")" && pwd)"
kRoot="$(cd "$kHere/../.." && pwd)"
kRepo="https://github.com/JetBrains/compose-multiplatform-core"
kRef="$(grep -v '^[[:space:]]*#' "$kHere/compose-ref.txt" | head -1 | tr -d '[:space:]')"
kSrc="${CMP_REF:-$kRoot/../cmp-ref}"

if [ -z "$kRef" ]; then echo "no ref in compose-ref.txt" >&2; exit 1; fi

# ── 1. Ensure a sparse clone at the pinned ref ────────────────────────────
if [ ! -d "$kSrc/.git" ]; then
	echo "cloning $kRepo -> $kSrc (sparse: ui/foundation/animation)"
	git clone --filter=blob:none --no-checkout "$kRepo" "$kSrc"
	git -C "$kSrc" sparse-checkout set compose/ui compose/foundation compose/animation
fi
git -C "$kSrc" checkout -q "$kRef" 2>/dev/null || {
	echo "ref $kRef not present locally — fetching"
	git -C "$kSrc" fetch origin "$kRef" && git -C "$kSrc" checkout -q "$kRef"
}
echo "upstream @ $(git -C "$kSrc" describe --tags --always)"

# ── 2. KDoc -> repo comment style (plain /* */, no leading stars) ──────────
conv() { sed -e 's#/\*\*#/*#g' -e 's#^\([[:space:]]*\)\* #\1#g' -e 's#^\([[:space:]]*\)\*$#\1#g'; }

# ── 3. Vendor each manifest entry ─────────────────────────────────────────
vCount=0
while read -r vUp vDest; do
	[ -z "${vUp:-}" ] && continue
	case "$vUp" in \#*) continue ;; esac
	if [ ! -f "$kSrc/$vUp" ]; then echo "MISSING upstream file: $vUp" >&2; exit 1; fi
	mkdir -p "$kRoot/$(dirname "$vDest")"
	{
		echo "// Vendored from JetBrains/compose-multiplatform-core@$kRef"
		echo "// upstream: $vUp"
		echo "// Generated by tools/compose-fork/sync.sh — DO NOT EDIT BY HAND."
		conv < "$kSrc/$vUp"
	} > "$kRoot/$vDest"
	echo "  vendored $vDest"
	vCount=$((vCount + 1))
done < <(grep -v '^[[:space:]]*#' "$kHere/manifest.txt" | grep -v '^[[:space:]]*$')

echo "synced $vCount files at $kRef"
