#!/usr/bin/env python3
# Compose-API fidelity check: diff this project's PUBLIC androidx.compose.* ABI
# against the official Compose klib ABI, flagging declarations we expose that
# upstream Compose does not (invented / divergent public surface).
#
# Inputs:
#   - our dumps:      <module>/api/<module>.klib.api  (generated by `./gradlew apiDump`,
#                     Kotlin binary-compatibility-validator plugin)
#   - official dumps: the JetBrains/compose-multiplatform-core clone's
#                     compose/**/api/*.klib.api  (default: C:/Dev/cmp-ref)
#
# Usage:  ./gradlew apiDump && python3 scripts/compose-fidelity-check.py [cmp-ref-dir]
#
# Both files use the same binary-compatibility-validator klib format, where each
# declaration carries a trailing `// <decl-id>|<mangle>` comment. We compare the
# <decl-id> path (normalised) as a set, so a name present in ours but not upstream
# is surfaced. NOTE: the reference clone is sparse (ui / foundation / animation /
# runtime) — material and desktop-only foundation (e.g. Scrollbar) have no upstream
# file here, so declarations in those areas show up as "not upstream" and are
# expected project surface, not bugs. Treat the output as candidates to review
# against CLAUDE.md's fidelity rules, not a hard gate.

import os
import sys
import re
from pathlib import Path

kRoot = Path(__file__).resolve().parent.parent
# cmp-ref clone: explicit arg, then $CMP_REF, then <repo>/../cmp-ref (where
# scripts/compose-fork/sync.sh puts it), then the old Windows default. Portable
# across Windows / macOS / Linux.
if len(sys.argv) > 1:
    kRefDir = Path(sys.argv[1])
elif os.environ.get("CMP_REF"):
    kRefDir = Path(os.environ["CMP_REF"])
elif (kRoot.parent / "cmp-ref").exists():
    kRefDir = kRoot.parent / "cmp-ref"
else:
    kRefDir = Path("C:/Dev/cmp-ref")

# decl-id is the text between "// " and the first "|". Strip accessor / ctor
# noise so a property and its getter collapse to one name.
_ACCESSOR = re.compile(r"\.<(get|set)-[^>]+>$")


def decl_ids(in_path):
    vIds = set()
    for vLine in in_path.read_text(encoding="utf-8", errors="ignore").splitlines():
        vIdx = vLine.find("// ")
        if vIdx < 0:
            continue
        vId = vLine[vIdx + 3:].split("|", 1)[0].strip()
        if not vId.startswith("androidx.compose"):
            continue
        if "$stable" in vId:   # Compose-compiler-generated stability props — not real API
            continue
        vId = _ACCESSOR.sub("", vId)
        vId = re.sub(r"\.<init>.*$", "", vId)   # constructors -> owning class
        vIds.add(vId)
    return vIds


def package_of(in_id):
    # "androidx.compose.ui.unit/Density.toDpSize" -> "androidx.compose.ui.unit"
    return in_id.split("/", 1)[0]


def main():
    vOfficial = set()
    vRefFiles = sorted(kRefDir.glob("compose/**/api/*.klib.api"))
    for vF in vRefFiles:
        vOfficial |= decl_ids(vF)
    if not vOfficial:
        print(f"!! No official klib.api found under {kRefDir} — clone JetBrains/compose-multiplatform-core there.")
        return 1

    vOurFiles = sorted(kRoot.glob("*/api/*.klib.api")) + sorted(kRoot.glob("*/*/api/*.klib.api"))
    if not vOurFiles:
        print("!! No local api/*.klib.api dumps — run `./gradlew apiDump` first.")
        return 1

    vOurs = {}
    for vF in vOurFiles:
        for vId in decl_ids(vF):
            vOurs.setdefault(vId, vF.parent.parent.name)

    vDivergent = sorted(set(vOurs) - vOfficial)
    print(f"Official refs: {len(vRefFiles)} klib.api files, {len(vOfficial)} androidx.compose.* decls")
    print(f"Our dumps:     {len(vOurFiles)} files, {len(vOurs)} androidx.compose.* decls")
    print(f"Not found in upstream Compose: {len(vDivergent)} decls\n")

    vByPkg = {}
    for vId in vDivergent:
        vByPkg.setdefault(package_of(vId), []).append(vId)
    for vPkg in sorted(vByPkg):
        print(f"  [{vPkg}]  ({len(vByPkg[vPkg])})")
        for vId in vByPkg[vPkg]:
            print(f"      {vId.split('/', 1)[1]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
